src/platform-data-model/application-log/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <label>Application Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/platform-data-model/application-log/objects/Application_Log__c/fields/Application_Domain__c.field-meta.xml
<CustomField>
    <fullName>Application_Domain__c</fullName>
    <description>Specifies which area of the application the application log is connected to.</description>
    <label>Application Domain</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Application_Domain</valueSetName>
    </valueSet>
</CustomField>

src/platform-data-model/globalValueSets/Application_Domain.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NKS</fullName>
    </customValue>
    <customValue>
        <fullName>HOT</fullName>
    </customValue>
    <customValue>
        <fullName>POAB</fullName>
    </customValue>
    <customValue>
        <fullName>AAREG</fullName>
    </customValue>
    <customValue>
        <fullName>CRM</fullName>
    </customValue>
    <customValue>
        <fullName>IPS</fullName>
    </customValue>
    <customValue>
        <fullName>AVVIK</fullName>
        <label>Avvik</label>
    </customValue>
    <customValue>
        <fullName>PLATFORCE</fullName>
        <label>Platforce</label>
    </customValue>
    <description>List of teams. Mirrors CRM_ApplicationDomain.Domain</description>
    <masterLabel>Application Domain</masterLabel>
</GlobalValueSet>

src/application-monitoring/test/classes/LoggerUtility_Test.cls
/**
 * @description Unit tests for the LoggerUtility class.
 */
@IsTest(isParallel=true)
public class LoggerUtility_Test {
    @IsTest
    public static void testLogging() {
        LoggerUtility logger = new LoggerUtility();

        logger.info('Testing info logging', null);
        logger.error('Testing error logging', null);
        logger.warning('Testing warning logging', null);
        logger.critical('Testing critical logging', null);

        try {
            Integer i = 1 / 0;
        } catch (Exception ex) {
            logger.exception(ex);
            logger.exception(ex, new Account());
        }

        logger.peek();

        Test.startTest();
        logger.publish();
        Test.stopTest();

        System.assert([SELECT COUNT() FROM Application_Log__c] == 6);
    }

    @IsTest
    public static void testLoggingDomain() {
        LoggerUtility logger = new LoggerUtility();

        logger.setCategory('Test');

        logger.info(
            'Testing info logging',
            null,
            CRM_ApplicationDomain.Domain.NKS
        );
        logger.error(
            'Testing error logging',
            null,
            CRM_ApplicationDomain.Domain.NKS
        );
        logger.warning(
            'Testing warning logging',
            null,
            CRM_ApplicationDomain.Domain.NKS
        );
        logger.critical(
            'Testing critical logging',
            null,
            CRM_ApplicationDomain.Domain.NKS
        );

        try {
            Integer i = 1 / 0;
        } catch (Exception ex) {
            logger.exception(ex, CRM_ApplicationDomain.Domain.NKS);
        }

        logger.peek();

        Test.startTest();
        logger.publish();
        Test.stopTest();

        System.assert([SELECT COUNT() FROM Application_Log__c] == 5);
    }

    @IsTest
    public static void testLoggingHttpError() {
        LoggerUtility logger = new LoggerUtility();

        HttpResponse response = new HttpResponse();
        response.setStatusCode(400);
        response.setBody('Http body');
        response.setStatus('Error status');

        logger.httpError(
            'Test logging http error',
            response,
            null,
            CRM_ApplicationDomain.Domain.NKS
        );

        Test.startTest();
        logger.publish();
        Test.stopTest();

        System.assert([SELECT COUNT() FROM Application_Log__c] == 1);
    }

    @isTest
    public static void testPublishSynch() {
        LoggerUtility logger = new LoggerUtility();

        logger.info('Testing info logging', null);
        logger.error('Testing error logging', null);
        logger.warning('Testing warning logging', null);
        logger.critical('Testing critical logging', null);

        Test.startTest();
        logger.publishSynch();
        Test.stopTest();

        System.assert(
            [SELECT COUNT() FROM Application_Log__c] == 4,
            'Invalid log amount: ' + [SELECT COUNT() FROM Application_Log__c]
        );
    }

    @IsTest
    private static void getUuid() {
        String uuid;
        Test.startTest();
        uuid = LoggerUtility.getUuid();
        Test.stopTest();

        System.Assert.isTrue(String.isNotBlank(uuid), 'UUID is blank');
    }

    @isTest
    public static void testHandleLogRequests() {
        LoggerUtility.LogRequest logReq1 = new LoggerUtility.LogRequest();
        LoggerUtility.LogRequest logReq2 = new LoggerUtility.LogRequest();
        LoggerUtility.LogRequest logReq3 = new LoggerUtility.LogRequest();
        LoggerUtility.LogRequest logReq4 = new LoggerUtility.LogRequest();

        logReq1.logLevel = 'INFO';
        logReq1.source = 'TEST';
        logReq1.logMessage = 'MESSAGE';

        logReq2.logLevel = 'WARNING';
        logReq2.source = 'TEST';
        logReq2.logMessage = 'MESSAGE';

        logReq3.logLevel = 'ERROR';
        logReq3.source = 'TEST';
        logReq3.logMessage = 'MESSAGE';

        logReq4.logLevel = 'CRITICAL';
        logReq4.source = 'TEST';
        logReq4.logMessage = 'MESSAGE';

        Test.startTest();
        LoggerUtility.handleLogRequests(
            new List<LoggerUtility.LogRequest>{
                logReq1,
                logReq2,
                logReq3,
                logReq4
            }
        );
        Test.stopTest();

        System.assert([SELECT COUNT() FROM Application_Log__c] == 4);
    }

    /**
     * Ensure that the domain can be set in the constructor. Also ensure that
     * this can be overridden in calls to logMessage.
     */
    @IsTest
    public static void constructDomain() {
        LoggerUtility logger = new LoggerUtility(
            CRM_ApplicationDomain.Domain.NKS,
            'Test'
        );
        logger.info('Testing info logging', null);
        logger.logMessage(
            LoggerUtility.logLevel.Info,
            null,
            null,
            'Testing separate domain logging',
            JSON.serializePretty(null),
            null,
            CRM_ApplicationDomain.Domain.HOT
        );
        Test.startTest();
        logger.publish();
        Test.stopTest();
        Assert.areEqual(
            1,
            [
                SELECT COUNT()
                FROM Application_Log__c
                WHERE Application_Domain__c = 'NKS'
            ]
        );
        Assert.areEqual(
            1,
            [
                SELECT COUNT()
                FROM Application_Log__c
                WHERE Application_Domain__c = 'HOT'
            ]
        );
    }

    /**
     * Ensure that not setting the domain in the constructor is still fine.
     */
    @IsTest
    public static void doNotConstructDomain() {
        LoggerUtility logger = new LoggerUtility('Test');
        logger.info('Testing info logging', null);
        Test.startTest();
        logger.publish();
        Test.stopTest();
        Assert.areEqual(1, [SELECT COUNT() FROM Application_Log__c]);
        Application_Log__c entry = [
            SELECT Application_Domain__c
            FROM Application_Log__c
            LIMIT 1
        ];
        Assert.isNull(entry.Application_Domain__c);
    }
}