src/platform-data-model/application-log/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <label>Application Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/platform-data-model/application-log/objects/Application_Log__c/fields/Application_Domain__c.field-meta.xml
<CustomField>
    <fullName>Application_Domain__c</fullName>
    <description>Specifies which area of the application the application log is connected to.</description>
    <label>Application Domain</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Application_Domain</valueSetName>
    </valueSet>
</CustomField>

src/platform-data-model/application-log/objects/Application_Log__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Category within application domain to allow for further filtering og logs.</description>
    <label>Category</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

src/platform-data-model/application-log/objects/Application_Log__c/fields/Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Log_Level__c</fullName>
    <label>Log Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/platform-data-model/application-log/objects/Application_Log__c/fields/Log_Message__c.field-meta.xml
<CustomField>
    <fullName>Log_Message__c</fullName>
    <label>Log Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/platform-data-model/application-log/objects/Application_Log__c/fields/Source_Class__c.field-meta.xml
<CustomField>
    <fullName>Source_Class__c</fullName>
    <label>Source Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/platform-data-model/application-log-setting-custom-metadata/objects/Application_Log_Setting__mdt/Application_Log_Setting__mdt.object-meta.xml
<CustomObject>
    <description
    >Custom metadata to configure settings for sending application logs to defined slack channels.</description>
    <label>Application Log Setting</label>
    <pluralLabel>Application Log Settings</pluralLabel>
</CustomObject>

src/platform-data-model/application-log-setting-custom-metadata/objects/Application_Log_Setting__mdt/fields/Application_Domain__c.field-meta.xml
<CustomField>
    <fullName>Application_Domain__c</fullName>
    <description>Defines which part of the application that &quot;owns&quot; the log setting</description>
    <label>Application Domain</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NKS</fullName>
                <default>true</default>
                <label>NKS</label>
            </value>
            <value>
                <fullName>HOT</fullName>
            </value>
            <value>
                <fullName>POAB</fullName>
            </value>
            <value>
                <fullName>AAREG</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/platform-data-model/application-log-setting-custom-metadata/objects/Application_Log_Setting__mdt/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description
    >Required category to match for logs to be published to slack. Leave blank to only use minimum log level and application domain as criteria.</description>
    <inlineHelpText
    >Required category to match for logs to be published to slack. Leave blank to only use minimum log level and application domain as criteria.</inlineHelpText>
    <label>Category</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

src/platform-data-model/application-log-setting-custom-metadata/objects/Application_Log_Setting__mdt/fields/Immediate_Post__c.field-meta.xml
<CustomField>
    <fullName>Immediate_Post__c</fullName>
    <defaultValue>false</defaultValue>
    <description
    >Determines if the message should be posted immediately after logging, or can be handling in a separate aggregate error report.</description>
    <inlineHelpText
    >Determines if the message should be posted immediately after logging, or can be handling in a separate aggregate error report.</inlineHelpText>
    <label>Immediate Post</label>
    <type>Checkbox</type>
</CustomField>

src/platform-data-model/application-log-setting-custom-metadata/objects/Application_Log_Setting__mdt/fields/Message_Template__c.field-meta.xml
<CustomField>
    <fullName>Message_Template__c</fullName>
    <inlineHelpText>Template for the message to be posted to slack.</inlineHelpText>
    <label>Message Template</label>
    <type>TextArea</type>
</CustomField>

src/platform-data-model/application-log-setting-custom-metadata/objects/Application_Log_Setting__mdt/fields/Minimum_Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Log_Level__c</fullName>
    <description>The minimum log level required for posting a message.</description>
    <inlineHelpText>The minimum log level required for posting a message.</inlineHelpText>
    <label>Minimum Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
                <default>true</default>
                <label>Info</label>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/platform-data-model/application-log-setting-custom-metadata/objects/Application_Log_Setting__mdt/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>Unique name of the named credential to use to inject the Slack Hook.</description>
    <inlineHelpText>Unique name of the named credential to use to inject the Slack Hook.</inlineHelpText>
    <label>Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/platform-data-model/application-log-setting-custom-metadata/objects/Application_Log_Setting__mdt/fields/Slack_Hook__c.field-meta.xml
<CustomField>
    <fullName>Slack_Hook__c</fullName>
    <description>Slack hook the channel where the message should be posted</description>
    <inlineHelpText
    >Slack hook the channel where the message should be posted when running in a production org.</inlineHelpText>
    <label>Slack Hook</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

src/platform-data-model/application-log-setting-custom-metadata/objects/Application_Log_Setting__mdt/fields/Slack_Hook_Sandbox__c.field-meta.xml
<CustomField>
    <fullName>Slack_Hook_Sandbox__c</fullName>
    <description>Hook to a slack channel that should be published to when running in a non production org.</description>
    <inlineHelpText
    >Hook to a slack channel that should be published to when running in a non production org. Keep this blank if no publishing should be done from sandbox for this setting.</inlineHelpText>
    <label>Slack Hook Sandbox</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

src/platform-data-model/globalValueSets/Application_Domain.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NKS</fullName>
    </customValue>
    <customValue>
        <fullName>HOT</fullName>
    </customValue>
    <customValue>
        <fullName>POAB</fullName>
    </customValue>
    <customValue>
        <fullName>AAREG</fullName>
    </customValue>
    <customValue>
        <fullName>CRM</fullName>
    </customValue>
    <customValue>
        <fullName>IPS</fullName>
    </customValue>
    <customValue>
        <fullName>AVVIK</fullName>
        <label>Avvik</label>
    </customValue>
    <customValue>
        <fullName>PLATFORCE</fullName>
        <label>Platforce</label>
    </customValue>
    <description>List of teams. Mirrors CRM_ApplicationDomain.Domain</description>
    <masterLabel>Application Domain</masterLabel>
</GlobalValueSet>

src/application-monitoring/main/classes/ApplicationLogPublisher.cls
@SuppressWarnings('PMD')
public class ApplicationLogPublisher {
    public static Application_Log_Setting__mdt testSetting;
    //Introduce setting to determine if messages should be published also for sandboxes
    private static Boolean isSandbox = [
        SELECT Id, isSandbox
        FROM Organization
        LIMIT 1
    ]
    .isSandbox;

    /**
     * @description: Performs a check on created application logs to see if any meet
     * the requirements for publishing to slack channels.
     * @author Stian Ruud Schikora | 02-23-2021
     * @param appLogs
     **/
    public static void publishLogs(List<Application_Log__c> appLogs) {
        Set<String> appDomains = new Set<String>();
        List<AppLog> logsToPublish = new List<AppLog>();

        for (Application_Log__c log : appLogs) {
            appDomains.add(log.Application_Domain__c);
        }

        List<Application_Log_Setting__mdt> logSettings = getLogSettings(
            appDomains
        );

        for (Application_Log__c log : appLogs) {
            for (Application_Log_Setting__mdt setting : logSettings) {
                if (
                    log.Application_Domain__c == setting.Application_Domain__c
                ) {
                    String hook = getHook(setting);
                    if (
                        getLogLevelOrdinal(log.Log_Level__c) >=
                        getLogLevelOrdinal(setting.Minimum_Log_Level__c) &&
                        setting.Category__c == log.Category__c
                    ) {
                        if (
                            Setting.Immediate_Post__c && String.isNotBlank(hook)
                        ) {
                            logsToPublish.add(
                                new AppLog(
                                    log,
                                    hook,
                                    Setting.Named_Credential__c,
                                    Setting.Message_Template__c
                                )
                            );
                        }
                    }
                } else {
                    continue;
                }
            }
        }

        if (!logsToPublish.isEmpty()) {
            //If there are more logs to publish than the transactional callout limit, generate several future contexts
            if (logsToPublish.size() > Limits.getLimitCallouts()) {
                List<AppLog> listToPublish = new List<AppLog>();
                while (logsToPublish.size() > 0) {
                    listToPublish.add(logsToPublish.remove(0));
                    if (listToPublish.size() == Limits.getLimitCallouts()) {
                        publishToSlack(JSON.serialize(listToPublish));
                        listToPublish.clear();
                    }
                }
            } else {
                publishToSlack(JSON.serialize(logsToPublish));
            }
        }
    }

    @future(Callout=true)
    private static void publishToSlack(String jsonAppLogs) {
        try {
            List<AppLog> logs = (List<AppLog>) JSON.deserialize(
                jsonAppLogs,
                List<AppLog>.class
            );
            SlackCalloutService slackCalloutService = new SlackCalloutService();

            for (AppLog log : logs) {
                SlackMessage message = new SlackMessage(log.messageTemplate);
                String errorMessage =
                    'Log level: ' +
                    log.logRecord.Log_Level__c +
                    '\n Source: ' +
                    log.logRecord.Source_Class__c +
                    '\n Link: ' +
                    URL.getSalesforceBaseUrl().toExternalForm() +
                    '/' +
                    log.logRecord.Id +
                    '\n Message: ' +
                    log.logRecord.Log_Message__c;
                message.addSection(errorMessage);

                slackCalloutService.postMessage(
                    log.namedCredential,
                    log.slackHook,
                    message
                );
            }
        } catch (Exception e) {
            System.debug(
                'Error occurred while publishing logs to Slack: ' +
                e.getMessage()
            );
        }
    }

    private static List<Application_Log_Setting__mdt> getLogSettings(
        Set<String> appDomains
    ) {
        if (Test.isRunningTest()) {
            return testSetting != null
                ? new List<Application_Log_Setting__mdt>{ testSetting }
                : new List<Application_Log_Setting__mdt>();
        }
        return [
            SELECT
                Id,
                MasterLabel,
                Application_Domain__c,
                Slack_Hook__c,
                Slack_Hook_Sandbox__c,
                Message_Template__c,
                Immediate_Post__c,
                Minimum_Log_Level__c,
                Named_Credential__c,
                Category__c
            FROM Application_Log_Setting__mdt
            WHERE Application_Domain__c IN :appDomains
        ];
    }

    //Returns the correct slack hook for production or sandbox.

    private static String getHook(Application_Log_Setting__mdt logSetting) {
        if (isSandbox) {
            return logSetting.Slack_Hook_Sandbox__c;
        }
        return logSetting.Slack_Hook__c;
    }

    // Returns the log level ordinal for a input loglevel string
    //INFO = 0, WARNING = 1, ERROR = 2, CRITICAL = 3

    private static Integer getLogLevelOrdinal(String logLevel) {
        return LoggerUtility.inverseLevelMap.get(logLevel).ordinal();
    }

    private class AppLog {
        private AppLog(
            Application_Log__c appLog,
            String slackHook,
            String namedCredential,
            String messageTemplate
        ) {
            this.logRecord = appLog;
            this.slackHook = slackHook;
            this.namedCredential = namedCredential;
            this.messageTemplate = messageTemplate;
        }

        private Application_Log__c logRecord;
        private String slackHook;
        private String namedCredential;
        private String messageTemplate;
    }
}