src/platform-data-model/application-log/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <label>Application Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/platform-data-model/application-log/objects/Application_Log__c/fields/Application_Domain__c.field-meta.xml
<CustomField>
    <fullName>Application_Domain__c</fullName>
    <description>Specifies which area of the application the application log is connected to.</description>
    <label>Application Domain</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Application_Domain</valueSetName>
    </valueSet>
</CustomField>

src/platform-data-model/application-log/objects/Application_Log__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Category within application domain to allow for further filtering og logs.</description>
    <label>Category</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

src/platform-data-model/application-log-setting-custom-metadata/objects/Application_Log_Setting__mdt/Application_Log_Setting__mdt.object-meta.xml
<CustomObject>
    <description
    >Custom metadata to configure settings for sending application logs to defined slack channels.</description>
    <label>Application Log Setting</label>
    <pluralLabel>Application Log Settings</pluralLabel>
</CustomObject>

src/platform-data-model/application-log-setting-custom-metadata/objects/Application_Log_Setting__mdt/fields/Application_Domain__c.field-meta.xml
<CustomField>
    <fullName>Application_Domain__c</fullName>
    <description>Defines which part of the application that &quot;owns&quot; the log setting</description>
    <label>Application Domain</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NKS</fullName>
                <default>true</default>
                <label>NKS</label>
            </value>
            <value>
                <fullName>HOT</fullName>
            </value>
            <value>
                <fullName>POAB</fullName>
            </value>
            <value>
                <fullName>AAREG</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/platform-data-model/application-log-setting-custom-metadata/objects/Application_Log_Setting__mdt/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description
    >Required category to match for logs to be published to slack. Leave blank to only use minimum log level and application domain as criteria.</description>
    <inlineHelpText
    >Required category to match for logs to be published to slack. Leave blank to only use minimum log level and application domain as criteria.</inlineHelpText>
    <label>Category</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

src/platform-data-model/application-log-setting-custom-metadata/objects/Application_Log_Setting__mdt/fields/Immediate_Post__c.field-meta.xml
<CustomField>
    <fullName>Immediate_Post__c</fullName>
    <defaultValue>false</defaultValue>
    <description
    >Determines if the message should be posted immediately after logging, or can be handling in a separate aggregate error report.</description>
    <inlineHelpText
    >Determines if the message should be posted immediately after logging, or can be handling in a separate aggregate error report.</inlineHelpText>
    <label>Immediate Post</label>
    <type>Checkbox</type>
</CustomField>

src/platform-data-model/application-log-setting-custom-metadata/objects/Application_Log_Setting__mdt/fields/Message_Template__c.field-meta.xml
<CustomField>
    <fullName>Message_Template__c</fullName>
    <inlineHelpText>Template for the message to be posted to slack.</inlineHelpText>
    <label>Message Template</label>
    <type>TextArea</type>
</CustomField>

src/platform-data-model/application-log-setting-custom-metadata/objects/Application_Log_Setting__mdt/fields/Minimum_Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Log_Level__c</fullName>
    <description>The minimum log level required for posting a message.</description>
    <inlineHelpText>The minimum log level required for posting a message.</inlineHelpText>
    <label>Minimum Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
                <default>true</default>
                <label>Info</label>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/platform-data-model/application-log-setting-custom-metadata/objects/Application_Log_Setting__mdt/fields/Slack_Hook__c.field-meta.xml
<CustomField>
    <fullName>Slack_Hook__c</fullName>
    <description>Slack hook the channel where the message should be posted</description>
    <inlineHelpText
    >Slack hook the channel where the message should be posted when running in a production org.</inlineHelpText>
    <label>Slack Hook</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

src/platform-data-model/application-log-setting-custom-metadata/objects/Application_Log_Setting__mdt/fields/Slack_Hook_Sandbox__c.field-meta.xml
<CustomField>
    <fullName>Slack_Hook_Sandbox__c</fullName>
    <description>Hook to a slack channel that should be published to when running in a non production org.</description>
    <inlineHelpText
    >Hook to a slack channel that should be published to when running in a non production org. Keep this blank if no publishing should be done from sandbox for this setting.</inlineHelpText>
    <label>Slack Hook Sandbox</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

src/platform-data-model/globalValueSets/Application_Domain.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NKS</fullName>
    </customValue>
    <customValue>
        <fullName>HOT</fullName>
    </customValue>
    <customValue>
        <fullName>POAB</fullName>
    </customValue>
    <customValue>
        <fullName>AAREG</fullName>
    </customValue>
    <customValue>
        <fullName>CRM</fullName>
    </customValue>
    <customValue>
        <fullName>IPS</fullName>
    </customValue>
    <customValue>
        <fullName>AVVIK</fullName>
        <label>Avvik</label>
    </customValue>
    <customValue>
        <fullName>PLATFORCE</fullName>
        <label>Platforce</label>
    </customValue>
    <description>List of teams. Mirrors CRM_ApplicationDomain.Domain</description>
    <masterLabel>Application Domain</masterLabel>
</GlobalValueSet>

src/application-monitoring/test/classes/ApplicationLogPublisher_Test.cls
@isTest
public class ApplicationLogPublisher_Test {
    private static final String category = 'TEST CATEGORY';

    @isTest
    static void testAppLogPublish() {
        SingleRequestMock mock = new SingleRequestMock(200, 'OK', '', null);
        Test.setMock(HttpCalloutMock.class, mock);

        Application_Log_Setting__mdt testSetting = new Application_Log_Setting__mdt(
            Application_Domain__c = 'NKS',
            Slack_Hook__c = 'https://slack.test.com',
            Slack_Hook_Sandbox__c = 'https://slack.test.com',
            Message_Template__c = 'TEST TEMPLATE',
            Immediate_Post__c = true,
            Minimum_Log_Level__c = 'Error',
            Category__c = category
        );

        LoggerUtility logger = new LoggerUtility(category);
        for (Integer i = 0; i < 101; i++) {
            logger.error('TESTING', null, CRM_ApplicationDomain.Domain.NKS);
        }

        Test.startTest();
        ApplicationLogPublisher.testSetting = testSetting;
        List<Application_Log__c> logs = logger.publishSynch(); //Do DML for trigger coverage
        ApplicationLogPublisher.publishLogs(logs); //Calling directly in static context to trigger testSettings
        Test.stopTest();
    }
}