src/platform-data-model/dependency-injection-mapping-custom-metadata/objects/DependencyInjectionMapping__mdt/DependencyInjectionMapping__mdt.object-meta.xml
<CustomObject>
    <description>Mapping for APEX Dependency Injection</description>
    <label>Dependency Injection Mapping</label>
    <pluralLabel>Dependency Injection Mappings</pluralLabel>
</CustomObject>

src/platform-data-model/dependency-injection-mapping-custom-metadata/objects/DependencyInjectionMapping__mdt/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <label>Apex Class</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/platform-data-model/dependency-injection-mapping-custom-metadata/objects/DependencyInjectionMapping__mdt/fields/Interface__c.field-meta.xml
<CustomField>
    <fullName>Interface__c</fullName>
    <label>Interface</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/platform-repository/main/classes/DependencyInjectionRepository.cls
public with sharing class DependencyInjectionRepository extends RepositoryBase {
    public String getApexClassByInterface(String interfaceName) {
        String query =
            'SELECT ApexClass__c FROM DependencyInjectionMapping__mdt WHERE Interface__c = \'' +
            interfaceName +
            '\' LIMIT 1';

        List<DependencyInjectionMapping__mdt> mappings = (List<DependencyInjectionMapping__mdt>) new CustomMetadataDAO()
            .getCustomMetadataRecords(query);

        if (mappings.isEmpty()) {
            return null;
        }

        return mappings[0].ApexClass__c;
    }
}